### ISSUE TITLE
Hi, do you still have this rom?

### ISSUE THREAD

**Issue by ShenKang4181** [Evolution-X-Devices/official_devices#1536]
![image](https://user-images.githubusercontent.com/50401776/167977611-b10e841a-0312-4fcc-a2f3-e03ed2636c38.png)
I can't find this anywhere, all links are dead, can you give me this rom?
![image](https://user-images.githubusercontent.com/50401776/167977645-37874844-48db-426b-b272-5e38d29b9f4e.png)
![image](https://user-images.githubusercontent.com/50401776/167977664-ffed900b-217e-4008-94b2-93e3b630b11a.png)

**Comment by Relms12345** [comment]
@ShenKang4181 read the XDA thread title. Very slowly and carefully.

**Comment by AnierinBliss** [comment]
COPE

**Comment by ShenKang4181** [comment]
Are all backups deleted? @Relms12345

**Comment by Stallix** [comment]
> Are all backups deleted? @Relms12345

It would've been publicly shared if it was still available. Now please stop pestering us for it.

**Comment by ShenKang4181** [comment]
It's okay, I still love you
@Stallix
