### ISSUE TITLE
Bluetooth crash after connect

### ISSUE THREAD

**Issue by Aiyzox** [Evolution-X-Devices/official_devices#1609]
hello, I made the last update of the system but I encounter a problem: when I connect a device in bluetooth, the bluetooth crashes and restarts in a loop.

**Comment by AnierinBliss** [comment]
You have yet to provide the device, build date, etc. Therefore this report isn't helpful in any sort of way. Closing

**Comment by Aiyzox** [comment]
![Screenshot_20220701-100407_Paramètres](https://user-images.githubusercontent.com/40886865/176852455-03ee182f-4149-4d9f-9e2e-a9f04327924c.png)
There is informations
