### ISSUE TITLE
Capitalize letters in the codename of Realme Q5 Pro/ Gt Neo 3T

### ISSUE THREAD

**Issue by PiotrZPL** [Evolution-X-Devices/official_devices#1975]
Most Realme devices have a codename in the form of `RMX1234`, for example `RMX2170`. The lack of capitalization of the letters in the codename of Realme Q5 Pro/ Gt Neo 3T causes some parsers to fail. I suggest changing the codename from `rmx3371` to `RMX3371` in your files, especially in [devices.json](https://github.com/Evolution-X-Devices/official_devices/blob/master/devices.json).

![Inconsistency in devices.json](https://user-images.githubusercontent.com/79166768/235629271-96c5f080-f834-4703-a9ce-16f7a1328cf5.png)
Inconsistency in devices.json

![Inconsistency on the website](https://user-images.githubusercontent.com/79166768/235629645-35cf23c6-af20-4189-84d1-a7f33e19e2a4.png)
Inconsistency on the website

**Comment by Stallix** [comment]
https://github.com/Evolution-X-Devices/official_devices/commit/5af63af8c1d0bf778251c32ffacdb68d642099c5

Should be addressed. Let us know your thoughts.

**Comment by PiotrZPL** [comment]
Yep, everything works now. Thank you!

**Comment by PiotrZPL** [comment]
Yep, everything works now. Thank you!
