### ISSUE TITLE
Where is the sdm845 kernel repo

### ISSUE THREAD

**Issue by unguardedsiamese** [Evolution-X-Devices/official_devices#958]
@AnierinBliss I know you are online, merge my contributions

**Comment by unguardedsiamese** [comment]
![sticker](https://user-images.githubusercontent.com/71759892/93994576-9dbb4500-fdc2-11ea-9699-37333385256f.png)

**Comment by unguardedsiamese** [comment]
@AnierinBliss could you stop? mr. private repo maker man?

**Comment by unguardedsiamese** [comment]
@AnierinBliss I know you are online, merge my contributions

**Comment by unguardedsiamese** [comment]
@AnierinBliss do you lose the ablilty to make this repo private?

**Comment by unguardedsiamese** [comment]
![image](https://user-images.githubusercontent.com/71759892/93996455-d9efa500-fdc4-11ea-8df4-a7b148c8f489.png)

**Comment by unguardedsiamese** [comment]
@AnierinBliss

**Comment by DarkAngelGR** [comment]
@unguardedsiamese how bout u stop this shit?
